name: build-and-test
on:
    workflow_dispatch:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build-app:
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 17
                  cache: 'maven'

            - name: Build with Maven
              run: mvn clean package -DskipTests=true

    unit-test:
        needs: build-app
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 17
                  cache: 'maven'

            - name: Unit Tests
              run: mvn clean test

    integration-test:
        needs: build-app
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 17
                  cache: 'maven'

            - name: Integration Tests
              run: mvn -Dskip.ut=true clean verify